apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: simple-ingress
 annotations:
   kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: taska3.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: task-a1-service
            port:
              number: 80
