apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-a1-deployment
  labels:
    app: task-a1-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-a1-service
  template:
    metadata:
      labels:
        app: task-a1-service
    spec:
      containers:
      - name: task-a1-service
        image: task-a
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: task-a1-service
spec:
  selector:
    app: task-a1-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
